spring.application.name=webclient-resilience-demo
# Circuit Breaker config
#resilience4j.circuitbreaker.instances.myService.sliding-window-size=10
#resilience4j.circuitbreaker.instances.myService.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.myService.wait-duration-in-open-state=5s
#resilience4j.circuitbreaker.instances.myService.permitted-number-of-calls-in-half-open-state=3
#
## Retry config
#resilience4j.retry.instances.myService.max-attempts=3
#resilience4j.retry.instances.myService.wait-duration=500ms
#resilience4j.retry.instances.myService.retry-exceptions=java.io.IOException,java.lang.RuntimeException
#
## Timeout
#resilience4j.timelimiter.instances.myService.timeout-duration=3		
## Monitor circuit breaker state via actuator
#management.endpoints.web.exposure.include=health,circuitbreakers,retries
#management.endpoint.health.show-details=always
#management.health.circuitbreakers.enabled=true