spring.application.name=GoldSilverApp

spring.datasource.url=jdbc:mysql://localhost:3306/metals_db
spring.datasource.username=root
spring.datasource.password=<Password>

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sign up free at https://metalpriceapi.com ? copy your API key
metal-price-api.base-url: https://api.metalpriceapi.com/v1/latest
metal-price-api.api-key: <Your API KEY>   # free tier: 100 requests/day
metal-price-api.base-currency: INR                 # Indian Rupees
